// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oarhrvwldudkkhhgqvgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hcmhydndsZHVka2toaGdxdmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDMzNTgsImV4cCI6MjA1ODQ3OTM1OH0.UcT4IUefUQxsSNjhrWgSe6OYbFd4rhWO1yUCKvWWmgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);